/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAboutRouteImport } from './routes/app/about'
import { Route as AppAiRouteImport } from './routes/app/ai'
import { Route as AppDataRouteImport } from './routes/app/data'
import { Route as AppProcessingRouteImport } from './routes/app/processing'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppDataIndexRouteImport } from './routes/app/data.index'
import { Route as AppDataNewRouteImport } from './routes/app/data.new'
import { Route as AppDataUpdateRouteImport } from './routes/app/data.update'
import { Route as AppReportsIndexRouteImport } from './routes/app/reports.index'
import { Route as AppReportsReportIdRouteImport } from './routes/app/reports.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessingRoute = AppProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDataIndexRoute = AppDataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDataRoute,
} as any)
const AppDataNewRoute = AppDataNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDataRoute,
} as any)
const AppDataUpdateRoute = AppDataUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => AppDataRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsReportIdRoute = AppReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AppReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/about': typeof AppAboutRoute
  '/app/ai': typeof AppAiRoute
  '/app/data': typeof AppDataRouteWithChildren
  '/app/processing': typeof AppProcessingRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/data/new': typeof AppDataNewRoute
  '/app/data/update': typeof AppDataUpdateRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/app/data/': typeof AppDataIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/about': typeof AppAboutRoute
  '/app/ai': typeof AppAiRoute
  '/app/processing': typeof AppProcessingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/data/new': typeof AppDataNewRoute
  '/app/data/update': typeof AppDataUpdateRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/app/data': typeof AppDataIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/about': typeof AppAboutRoute
  '/app/ai': typeof AppAiRoute
  '/app/data': typeof AppDataRouteWithChildren
  '/app/processing': typeof AppProcessingRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/data/new': typeof AppDataNewRoute
  '/app/data/update': typeof AppDataUpdateRoute
  '/app/reports/$reportId': typeof AppReportsReportIdRoute
  '/app/data/': typeof AppDataIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/register'
    | '/app/about'
    | '/app/ai'
    | '/app/data'
    | '/app/processing'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/data/new'
    | '/app/data/update'
    | '/app/reports/$reportId'
    | '/app/data/'
    | '/app/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/app/about'
    | '/app/ai'
    | '/app/processing'
    | '/app/settings'
    | '/app'
    | '/app/data/new'
    | '/app/data/update'
    | '/app/reports/$reportId'
    | '/app/data'
    | '/app/reports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/login'
    | '/register'
    | '/app/about'
    | '/app/ai'
    | '/app/data'
    | '/app/processing'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/data/new'
    | '/app/data/update'
    | '/app/reports/$reportId'
    | '/app/data/'
    | '/app/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data': {
      id: '/app/data'
      path: '/data'
      fullPath: '/app/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/processing': {
      id: '/app/processing'
      path: '/processing'
      fullPath: '/app/processing'
      preLoaderRoute: typeof AppProcessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data/': {
      id: '/app/data/'
      path: '/'
      fullPath: '/app/data/'
      preLoaderRoute: typeof AppDataIndexRouteImport
      parentRoute: typeof AppDataRoute
    }
    '/app/data/new': {
      id: '/app/data/new'
      path: '/new'
      fullPath: '/app/data/new'
      preLoaderRoute: typeof AppDataNewRouteImport
      parentRoute: typeof AppDataRoute
    }
    '/app/data/update': {
      id: '/app/data/update'
      path: '/update'
      fullPath: '/app/data/update'
      preLoaderRoute: typeof AppDataUpdateRouteImport
      parentRoute: typeof AppDataRoute
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/reports/$reportId': {
      id: '/app/reports/$reportId'
      path: '/$reportId'
      fullPath: '/app/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdRouteImport
      parentRoute: typeof AppReportsRoute
    }
  }
}

interface AppDataRouteChildren {
  AppDataNewRoute: typeof AppDataNewRoute
  AppDataUpdateRoute: typeof AppDataUpdateRoute
  AppDataIndexRoute: typeof AppDataIndexRoute
}

const AppDataRouteChildren: AppDataRouteChildren = {
  AppDataNewRoute: AppDataNewRoute,
  AppDataUpdateRoute: AppDataUpdateRoute,
  AppDataIndexRoute: AppDataIndexRoute,
}

const AppDataRouteWithChildren =
  AppDataRoute._addFileChildren(AppDataRouteChildren)

interface AppReportsRouteChildren {
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsReportIdRoute: AppReportsReportIdRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAiRoute: typeof AppAiRoute
  AppDataRoute: typeof AppDataRouteWithChildren
  AppProcessingRoute: typeof AppProcessingRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAiRoute: AppAiRoute,
  AppDataRoute: AppDataRouteWithChildren,
  AppProcessingRoute: AppProcessingRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
